Repository traefik/hub-agent-kubernetes, pull requests merged in 2022-08, with the labels that each got.

#8 chore: add user-agent
  pkg/acp/jwt/jwk.go
  pkg/alerting/client.go
  pkg/metrics/client.go
  pkg/metrics/scraper.go
  pkg/platform/client.go
  pkg/tunnel/client.go
  pkg/version/version.go
Labels: bot/light-review, kind/enhancement, status/3-needs-merge

#9 chore: bump to go1.19
  .github/workflows/branches.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .golangci.yml
  buildx.Dockerfile
  dev.Dockerfile
  go.mod
  pkg/crd/api/traefik/v1alpha1/ingressroute.go
  pkg/crd/api/traefik/v1alpha1/register.go
  pkg/crd/api/traefik/v1alpha1/service.go
  pkg/crd/api/traefik/v1alpha1/tlsoption.go
  pkg/metrics/protocol/protocol.go
  scripts/codegen.Dockerfile
Labels: kind/enhancement, status/3-needs-merge, area/infrastructure

#10 fix: codegen dockerfile
  scripts/codegen.Dockerfile
Labels: kind/bug/fix, status/3-needs-merge

#7 Add OIDC ACP
  .golangci.yml
  cmd/agent/auth_server.go
  go.mod
  go.sum
  pkg/acp/admission/event_handler.go
  pkg/acp/admission/reviewer/ingress.go
  pkg/acp/admission/reviewer/traefik_ingress_test.go
  pkg/acp/auth/watcher.go
  pkg/acp/auth/watcher_test.go
  pkg/acp/config.go
  pkg/acp/jwt/jwt.go
  pkg/acp/oidc/config.go
  pkg/acp/oidc/cookie.go
  pkg/acp/oidc/cookie_test.go
  pkg/acp/oidc/http.go
  pkg/acp/oidc/http_test.go
  pkg/acp/oidc/mock_gen_test.go
  pkg/acp/oidc/mock_test.go
  pkg/acp/oidc/oidc.go
  pkg/acp/oidc/oidc_test.go
  pkg/acp/oidc/tls.go
  pkg/acp/watcher.go
  pkg/crd/api/hub/v1alpha1/access_control_policy.go
  pkg/crd/api/hub/v1alpha1/edge_ingress.go
  pkg/crd/api/hub/v1alpha1/zz_generated.deepcopy.go
  pkg/crd/generated/client/hub/clientset/versioned/fake/register.go
  pkg/crd/generated/client/hub/clientset/versioned/scheme/register.go
  pkg/crd/generated/client/traefik/clientset/versioned/fake/register.go
  pkg/crd/generated/client/traefik/clientset/versioned/scheme/register.go
  scripts/code-gen.sh
Labels: kind/enhancement, status/3-needs-merge
